export const permissions = {
  admin: [
    "home",
    "dashboard_gerencial",
    "vehicles",
    "clients",
    "directo",
    "cuotared",
    "budgets",
    "budget-reports",
    "reservations",
    "reservation-list",
    "refunds",
    "sales",
    "sales-list",
    "installment-payments",
    "installments",
    "settings",
    "users",
    "roles",
    "audit",
  ],

owner: [
  "home",
  "vehicles",
  "clients",
  "directo",
  "cuotared",
  "budgets",
  "budget-reports",
  "reservations",
  "reservation-list",
  "refunds",
  "sales",
  "sales-list",
  "installment-payments",
  "installments",
  "settings",
  "audit",
],

  vendedor: [
    "home",
    "vehicles",
    "clients",
    "directo",
    "cuotared",
    "budgets",
    "budget-reports",
    "reservations",
    "reservation-list",
    "sales",
  ],

  // ✅ NUEVO: vendedor de motos (mismo acceso funcional que vendedor, pero backend filtra motos)
  vendedor_motos: [
    "home",
    "vehicles",
    "clients",
    "directo",
    "cuotared",
    "budgets",
    "budget-reports",
    "reservations",
    "reservation-list",
    "sales",
  ],

  // ✅ NUEVO: vendedor de autos (mismo acceso funcional que vendedor, pero backend filtra motos)
  vendedor_autos: [
    "home",
    "vehicles",
    "clients",
    "directo",
    "cuotared",
    "budgets",
    "budget-reports",
    "reservations",
    "reservation-list",
    "sales",
  ],

  preventa_motos: [
    "home",
    "directo",
    "cuotared",
  ],

  gerencia: [
    "home",
    "vehicles",
    "clients",
    "directo",
    "cuotared",
    "budgets",
    "budget-reports",
    "reservations",
    "reservation-list",
    "refunds",
    "sales",
    "sales-list",
    "settings",
  ],

  viewer: [
    "home",
    "vehicles",
  ],

  legales: [
    "home",
    "vehicles",
    "clients",
    "directo",
    "cuotared",
    "budget-reports",
    "reservation-list",
    "refunds",
    "sales-list",
    "installment-payments",
    "installments",
  ],
};