export const permissions = {
  admin: [
    "home",
    "vehicles",
    "clients",
    "budgets",
    "budget-reports",
    "reservations",
    "reservation-list",
    "refunds",
    "sales",
    "sales-list",
    "installment-payments",
    "installments",
    "settings",
    "users",
    "roles",
    "audit",
  ],

  vendedor: [
    "home",
    "vehicles",
    "clients",
    "budgets",
    "budget-reports",
    "reservations",
    "reservation-list",
    "sales",
  ],

  gerencia: [
    "home",
    "vehicles",
    "clients",
    "budgets",
    "budget-reports",
    "reservations",
    "reservation-list",
    "refunds",
    "sales",
    "sales-list",
    "settings",
  ],

  legales: [
    "home",
    "vehicles",
    "clients",
    "budget-reports",
    "reservation-list",
    "refunds",
    "sales-list",
    "installment-payments",
    "installments",
  ],

  viewer: [
    "home",
    "vehicles",
  ],
};
